slots:
  survival:
    default-gamemode: survival
    worlds:
      - world
      - world_nether
      - world_ender
    allow-portals: true
    default-world: world
    save-position: true
    save-gamemode: true
    save-enderchest: true
    save-inventory: true
    save-potion: true
  creative:
    default-gamemode: creative
    worlds:
      - world_flatworld_flatworld
    allow-portals: false
    default-world: world_flatworld_flatworld
    save-position: true
    save-gamemode: true
    save-enderchest: true
    save-inventory: true
    save-potion: true

teleport-commands:
  main:
    world: world
  flat:
    world: world_flatworld_flatworld
